name: TabConfig
main: com.github.blockedup.infotab
version: 1
authors: [mpotacon, zdylann, Double0negative, MCSG]
depend: [TabAPI]

commands:
  tabapi:
    description: tabconfig
    usage: /tabconfig
    aliases: [tabconfig]
